apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: custom-cluster
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1c"]

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      allow: true
