apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-deploy
  labels:
    deploy: frontend
spec:
  replicas: 2
  selector:
      matchLabels:
        app: custom-nginx
        tier: frontend
  template:
    metadata:
        name: custom-nginx-pod
        labels:
            app: custom-nginx
            tier: frontend
    spec:
      containers:
      - name: nginx
        image: prashun08/custom-nginx:v3-release
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1