apiVersion: v1
kind: Pod
metadata:
  name: custom-nginx-pod
  labels:
    app: custom-nginx
    tier: frontend
spec:
  containers:
  - name: nginx
    image: prashun08/custom-nginx:v1-release
    ports:
    - containerPort: 80
    
