apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: custom-rs
  labels:
    rs: frontend
spec:
  replicas: 2
  selector:
      matchLabels:
        app: custom-nginx
        tier: frontend
  template:
    metadata:
        name: custom-nginx-pod
        labels:
            app: custom-nginx
            tier: frontend
    spec:
      containers:
      - name: nginx
        image: prashun08/custom-nginx:v2-release
        ports:
        - containerPort: 80