apiVersion: v1
kind: Service
metadata: 
  name: service-rs
spec:
  type: NodePort
  selector:
    app: custom-nginx
  ports:
  - name: httpd
    port: 80 # Service Port
    targetPort: 80 # Port of the Backend Pod
    nodePort: 31000 # Port of the Worker Node