apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
  - protocol: TCP
    port: 80                     #Service Port
    targetPort: 80               # Port of the Backend Pod
    nodePort: 30000              # Node Port